### ISSUE TITLE
Add Authentication 

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#12]
## Authentication & signing up 
Every app now days needs authentication to verify users as well as to keep data for each user creating a personalised experience 

## TODO:
- [x] Sign in / Signup dialog like how it is on [daily.dev](https://app.daily.dev/) 
- [x] Handle service providers such as google, apple, GitHub, etc
- [x] Handle email & password sign up - make it known as it being unsafe 
- [x] Make a way to do JWT auth with the API so I can do requests that way

**Comment by Eirfire** [comment]
#44 users can now sign in / sign up to Meally
