### ISSUE TITLE
📗 Bookmark recipes

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#13]
# Bookmark recipes for future use
Make a feature to save recipes for users to use in the future this all depends on #12 being finished beforehand so we can store user info on the server 
All bookmark icons are going to be love hearts ❤️ as it brings a different meaning to it as they "love the recipe"

## TODO:
- [x] Make sure all icons are Heart icons
- [x] Implement BookMark service or adjust the `UserService`
- [x] Make bookmarks have collections (Save them like the recipes under `users/<uid>/bookmark`) just like how we do recipes under the user profile
- [x] Toast to let the user know it was saved and which collection
- [x] Add a bookmark page (just use `getServerSideProps`)
- [x] Once implemented add this into the `[profile].tsx`
- [x] For search handle escaping on mobile 

## Bug fixes from #42 
- [x] fix submit error `_app-bcef9337d026d944.js:3032 Uncaught (in promise) FirebaseError: Missing or insufficient permissions.`\
- [x] Fix styling on imgUrl & imgAlt fields
- [ ] (Optional) fix validation for Time Inputs 
- [x]  Fix Github actions
- [x] Fix templates 

## Future implementations
- [ ] Figure out a fancy way of saving the recipe for the session and then posting it when the session finishes 
  _(this is a great feature to have in the future to reduce the number or writes to firestore however this can be done later when this accuually matters)

**Comment by Eirfire** [comment]
Everything has been fixed in #64
