### ISSUE TITLE
📑 Finish building out landing pages

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#2]
# Pages 
All landing pages need to build out, main pages that need to be built is the main page, recipe page, and sweet and savoury pages.

## Todo
- [x] Build Home page
- [x] Build Sweet landing page
- [x] Build Savouray landing page
- [x] Build Recipe page
- [ ] Make fully responsive
- [x] Add analytics

### design 
- [x] Design Homepage
- [x] Design Recipe page
- [x] Design Sweet page
- [x] Design Savoury page

### CI/CD
- [ ] Build errors and important warnings don't exist 
- [x] update to GitHub workflow for turbo 
- [ ] Better EsLint rules
- [ ] Maybe an editor config file
- [ ] Prettier config

**Comment by Eirfire** [comment]
All changes have now been made in #36 and is now ready for first beta release. any changes that need to be made from now on will be put into beta release 2
