### ISSUE TITLE
PWA, SEO, Accessibility, Performance, Best practices

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#25]
# Speed improvements
What needs to be done is to have all PWA, SEO, Accessibility, Performance, and Best practices between 90-100 score on lighthouse testing not just on desktop but also mobile.

## Fully offline support
In my app, I want to have fully offline support with users still being able to partially navigate without the internet and still be able to edit and create recipes and update data when they come online

#### PWA
Progress Web App is something that is becoming more and more needed easily with the app I am building I am looking for speed and accessibility to users which with a user being able to download the app would be awesome to have

#### Service worker and a CDN
Adding a service worker and a CDN to help with offline support, however, all we need to worry about is the Service worker. Thank you NextJs

# Todo:
- [x] Add PWA for offline support see [example](https://github.com/vercel/next.js/tree/canary/examples/progressive-web-app)
- [x] Improve overall accessibility 
- [x] Imrpove mobile scores
- [x] Service worker
- [x] Improve SEO 
- [x] turn my app into Nextjs 13 
- [x] use Turborepo and Turbopack or optimise my code. 
- [x] Add sitemaps
- [x] PWA improvements 
- [x] Better meta tags
The best decision would probably be to do both 
![image](https://user-images.githubusercontent.com/77374574/209883542-02673e28-d4fd-41b2-b5c5-656bb035f54a.png)

**Comment by Eirfire** [comment]
Fixed in all the issues in beta release 2
