### ISSUE TITLE
🧹 Project Cleanup

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#28]
# Project Clean up
overall the project needs a good cleaning up whether that is cleaner code or a better file structure or even better issue templates

## TODO:
- [x] File restructure
- [x] Rewrite components for readability and speed
- [x] Recipe Page & form bug fixes #38 
- [x] Clean up of styles
- [x] Make sure all packages are up to date with the latest version
- [x] Document the project better
- [x] Restructure of packages directory 
- [x] go through and rewrite components
- [x] Add documentation for components in Ui

### Github
- [x] Github actions workflows on Meally & UI 
- [x] New GitHub issues templates using .yml
- [x] Update to security policy 
- [x] Update to Contributing docs (Linked to Getting started guide as well)
