### ISSUE TITLE
🧑‍💻User profile

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#39]
## Ability for a user to change their profile info 
Along with Authentication #12 a user profile is something Meally needs so users can view their saved recipe, change their settings, etc

## TODO:
- [x] Update to navbar to check when a user is signed in 
- [x] User can click on their profile and see a drop down with options 
- [x] Settings page
- [ ] Bookmark page  #13 
- [x] Profile page like how they have on [medium](https://medium.com/)

**Comment by Eirfire** [comment]
All finished now just a few new updates that need to be made before it completely finished which will be coved in other tickets. #55
