### ISSUE TITLE
Backend switch Firestore & storage -> mongoDB

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#43]
# Why switch 
Overall if my app gets popular I will be storing a lot of data and the read / write costs will end up being quite huge along with all the little bits of data I will have to store it can be a problem.

This has to be fixed early so it isn't a huge challenge converting data from one provider to another down the track.

I will still use firebase for Auth & analytics along with this change it will make it possible to change search provider from Alolia to custom implementation 

## TODO:
- [ ] Learn more about mongoDB
- [ ] Check pricing and setup difficulty 
- [ ] Setup MongoDB in Meally
- [ ] Transfer any data from firebase over 
- [ ] Add API available for reading data through JWT

**Comment by Eirfire** [comment]
At this point after checking out the pricing calculator It should be ok in terms of pricing and if not we can work something out with going either to azure or GCP
