### ISSUE TITLE
Nutrition Values on recipes

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#45]
# Nurtrition values 
People have been more interested in these statistics than ever and something that would be great for users to see whenever they make a meal which will be calculated on the server side of things

## TODO:

- [ ] Figure out how these measures are calculated 
- [ ] See if it is possible to do these measures on the server
- [ ] Design where this would go on the recipe page
- [ ] Implement the measures
