### ISSUE TITLE
⏱️ Cooking timer

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#46]
# Cooking timers on recipes
For every recipe there is going to be a set about of time, something has to cook or sit and it would be a nice feature if a user could click a button on one of the steps to start the timer. It would show a little dialogue down the bottom right with a countdown timer, and it will go bing when complete.

## TODO:
- [ ] Figure out how to calculate time or find the time in the step 
- [ ] Implement a button to open the timer dialog and start the timer
- [ ] Create the timer and a count down function 
- [ ] Figure out how to make it go off - and go off when the device is off e.g mobile
