### ISSUE TITLE
🔀 Ingredient substitution 

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#47]
# Swap an ingredient for another one
When users sign up in their settings it would be cool if they can set their preference as Gluten Free for example and then on the recipe it will automatically substitute the item for the one that has been selected in their settings.

## TODO:
- [ ] Implement the settings feature #39 
- [ ] Add the substitution field/preference
- [ ] In the recipe add the change with a crossed item below the substituted item
