### ISSUE TITLE
🤖 AI intergrations

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#50]
# AI / Machine learning 
this has become so big over the past year and will probably continue to do so and with such a hype around it, it would be great to implement such a feature.

One way is for users to upload an image of the ingredients that they have and than get back a thing of what they can make with it with my services than find all the links to those recipe/Mealy suggestions. 
Something else is to use Machine learning to personise a users page / recipe selections. 

## TODO:
- [ ] Think up ways to use AI & Machine learning
- [ ] Get access to GPT-4 API
- [ ] Learning machine learning and how to integrate into an app.
