### ISSUE TITLE
Accessibility for people with disabilities

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#54]
Creating a place where people with certain disadvantages is at the forefront of what Meally is all about.

What are some ways we can help make our platform more accessible? Well add Aria labels, add proper Alt tags to images, different types for easier reading e.g dyslexic, supporting colour blind.

## TODO
- [ ] Add Aria labels to items that need it
- [ ] Alt tags to all images 
- [ ] In preferences add the support for the different types have a look at [DEV community](https://dev.to) for how they have implemented this
- [ ] Have a look at how to support people who are colour blind 
- [ ] Have a look at [IBM](https://www.ibm.com/able/) for ideas
