### ISSUE TITLE
🧾 View history 

### ISSUE THREAD

**Issue by Eirfire** [Eirfire/Meally#56]
# History 
View history of recipes will be great for future implementations so we can use machine learning models to create a customized experience for the user along with customization for the user it can help a user easily find a recipe they viewed a week ago.

## TODO:
- [ ] Track when a user goes on a recipe
- [ ] Update user -> history (figure out how it will be saved, possible session storage than updated in firestore)
- [ ] Update Privacy Policy & Terms of Service
